spring:
  application:
    name: respond-read-service

  #DB INFO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "admin"
    url: jdbc:mysql://210.109.60.250:10053/uniqdb?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=UTC&useSSL=false

  # profiles:
  #   active: dev

  #JPA/Hibernate
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show-sql: true
    show-sql: 'true'

  #Admin Server Client
  boot:
    admin:
      client:
        url: http://localhost:9090 # Spring Boot Admin Server URL
        instance:
          metadata:
            # Spring Boot Admin Server에서 Client의 Actuator endpoint에 접근 인증시 사용
            user:
              name: respond-read-service
              password: respond-read-service
        # Client가 Spring Boot Admin에 접근 인증시 사용
        username: admin
        password: admin

server:
  port: 8085

eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

#Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
#Kakao
#security:
#  oauth2:
#    client:
#      provider:
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#          user-name-attribute: id
#      registration:
#        kakao:
#          authorization-grant-type: authorization_code
#          client-authentication-method: POST
#          client-id: 94f0773a9ed776ce63552c0e82b1bb2a
#          client-name: Kakao
#          client-secret: VxNZrRES7xYSRs980yPB9MF3N5ntXh9A
#          redirect-uri: http://210.109.62.78:8080/login/oauth2/code/kakao
#          scope: profile_nickname, account_email