eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: zuul-api-gateway
  profiles:
    active:
      default

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes

server:
  port: 8080

zuul:
  ignored-services: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-service:
      path: /user-service/**
    survey-read-service:
      path: /survey-read-service/**
    survey-write-service:
      path: /survey-write-service/**
    respond-read-service:
      path: /respond-read-service/**
    respond-write-service:
      path: /respond-write-service/**
      url: http://localhost:8084


