eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: zuulservice
  profiles:
    active:
      default

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: routes

server:
  port: 8080

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    user-service: /user-service/**
    survey-read-service: /survey-read-service/**
    survey-write-service: /survey-write-service/**
    respond-read-service: /respond-read-service/**
    respond-write-service: /respond-write-service/**