server:
  port: 9090

spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        brand: <img src="assets/img/icon-spring-boot-admin.svg"><span>Spring Boot Admin</span>
        title: Spring Boot Admin