spring:
  application:
    name: survey-write-service

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

server:
  port: 8082

#spring:
#  profiles:
#    active: dev

#DB INFO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: continew
    password: continew36524
    url: jdbc:mysql://210.109.60.250:10007/uniqdb?zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8&connectTimeout=2000&autoReconnect=true&serverTimezone=UTC&useSSL=false


  #JPA/Hibernate
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        show-sql: true
    show-sql: 'true'

#Logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: DEBUG
#Kakao
#security:
#  oauth2:
#    client:
#      provider:
#        kakao:
#          authorization-uri: https://kauth.kakao.com/oauth/authorize
#          token-uri: https://kauth.kakao.com/oauth/token
#          user-info-uri: https://kapi.kakao.com/v2/user/me
#          user-name-attribute: id
#      registration:
#        kakao:
#          authorization-grant-type: authorization_code
#          client-authentication-method: POST
#          client-id: 94f0773a9ed776ce63552c0e82b1bb2a
#          client-name: Kakao
#          client-secret: VxNZrRES7xYSRs980yPB9MF3N5ntXh9A
#          redirect-uri: http://210.109.62.78:8080/login/oauth2/code/kakao
#          scope: profile_nickname, account_email